# Generated by Django 3.2.3 on 2021-09-21 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('description', models.TextField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('book_cover', models.ImageField(default='mockup1.png', upload_to='book_covers/')),
                ('book_cover1', models.ImageField(default='pages.png', upload_to='book_covers/')),
                ('book_cover2', models.ImageField(default='pages.png', upload_to='book_covers/')),
                ('book_cover3', models.ImageField(default='pages.png', upload_to='book_covers/')),
                ('have_book_cover', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('pup_date', models.DateField()),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.authors')),
            ],
        ),
    ]
